//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}Description"/>
 *         &lt;element name="IsDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="StatNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}GLRevenue" minOccurs="0"/>
 *         &lt;element ref="{}GLCosts" minOccurs="0"/>
 *         &lt;element ref="{}GLPurchase" minOccurs="0"/>
 *         &lt;element name="GLPurchasePriceDifference" type="{}typeGLAccount" minOccurs="0"/>
 *         &lt;element name="GLStockVariance" type="{}typeGLAccount" minOccurs="0"/>
 *         &lt;element name="GLPurchaseAccount" type="{}typeGLAccount" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}number"/>
 *       &lt;attribute ref="{}code"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "isDefault",
    "statNumber",
    "glRevenue",
    "glCosts",
    "glPurchase",
    "glPurchasePriceDifference",
    "glStockVariance",
    "glPurchaseAccount"
})
@XmlRootElement(name = "Assortment")
public class Assortment {

    @XmlElement(name = "Description")
    protected TypeDescription description;
    @XmlElement(name = "IsDefault")
    protected Boolean isDefault;
    @XmlElement(name = "StatNumber")
    protected String statNumber;
    @XmlElement(name = "GLRevenue")
    protected TypeGLAccount glRevenue;
    @XmlElement(name = "GLCosts")
    protected TypeGLAccount glCosts;
    @XmlElement(name = "GLPurchase")
    protected TypeGLAccount glPurchase;
    @XmlElement(name = "GLPurchasePriceDifference")
    protected TypeGLAccount glPurchasePriceDifference;
    @XmlElement(name = "GLStockVariance")
    protected TypeGLAccount glStockVariance;
    @XmlElement(name = "GLPurchaseAccount")
    protected TypeGLAccount glPurchaseAccount;
    @XmlAttribute(name = "number")
    protected BigInteger number;
    @XmlAttribute(name = "code")
    protected String code;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setDescription(TypeDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the isDefault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDefault() {
        return isDefault;
    }

    /**
     * Sets the value of the isDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDefault(Boolean value) {
        this.isDefault = value;
    }

    /**
     * Gets the value of the statNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatNumber() {
        return statNumber;
    }

    /**
     * Sets the value of the statNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatNumber(String value) {
        this.statNumber = value;
    }

    /**
     * Gets the value of the glRevenue property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLRevenue() {
        return glRevenue;
    }

    /**
     * Sets the value of the glRevenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLRevenue(TypeGLAccount value) {
        this.glRevenue = value;
    }

    /**
     * Gets the value of the glCosts property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLCosts() {
        return glCosts;
    }

    /**
     * Sets the value of the glCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLCosts(TypeGLAccount value) {
        this.glCosts = value;
    }

    /**
     * Gets the value of the glPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLPurchase() {
        return glPurchase;
    }

    /**
     * Sets the value of the glPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLPurchase(TypeGLAccount value) {
        this.glPurchase = value;
    }

    /**
     * Gets the value of the glPurchasePriceDifference property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLPurchasePriceDifference() {
        return glPurchasePriceDifference;
    }

    /**
     * Sets the value of the glPurchasePriceDifference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLPurchasePriceDifference(TypeGLAccount value) {
        this.glPurchasePriceDifference = value;
    }

    /**
     * Gets the value of the glStockVariance property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLStockVariance() {
        return glStockVariance;
    }

    /**
     * Sets the value of the glStockVariance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLStockVariance(TypeGLAccount value) {
        this.glStockVariance = value;
    }

    /**
     * Gets the value of the glPurchaseAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLPurchaseAccount() {
        return glPurchaseAccount;
    }

    /**
     * Sets the value of the glPurchaseAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLPurchaseAccount(TypeGLAccount value) {
        this.glPurchaseAccount = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
