//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PayrollYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{}Agency"/>
 *         &lt;element ref="{}StartDate"/>
 *         &lt;element ref="{}EndDate" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeAmountField01" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField02" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField03" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField04" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField05" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField06" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField07" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField08" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField09" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField10" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField11" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField12" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField13" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField14" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField15" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField16" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField17" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField18" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField19" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField20" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField21" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField22" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField23" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField24" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField25" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField26" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField27" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField28" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField29" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeAmountField30" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FreeDateField01" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField02" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField03" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField04" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField05" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField06" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField07" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField08" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField09" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeDateField10" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField01" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField02" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField03" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField04" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField05" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField06" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField07" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField08" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField09" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField10" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField11" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField12" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField13" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField14" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField15" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField16" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField17" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField18" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField19" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeNoYesField20" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FreeTextField01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField05" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField06" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField07" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField08" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField09" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField13" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField14" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField15" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField16" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField17" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField18" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField19" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField20" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField21" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField22" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField23" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField24" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField25" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField26" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField27" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField28" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField29" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField30" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField31" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField32" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField33" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField34" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField35" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField36" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField37" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField38" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField39" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextField40" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeIntField01" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField02" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField03" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField04" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField05" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField06" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField07" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField08" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField09" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FreeIntField10" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "payrollYear",
    "agency",
    "startDate",
    "endDate",
    "notes",
    "freeAmountField01",
    "freeAmountField02",
    "freeAmountField03",
    "freeAmountField04",
    "freeAmountField05",
    "freeAmountField06",
    "freeAmountField07",
    "freeAmountField08",
    "freeAmountField09",
    "freeAmountField10",
    "freeAmountField11",
    "freeAmountField12",
    "freeAmountField13",
    "freeAmountField14",
    "freeAmountField15",
    "freeAmountField16",
    "freeAmountField17",
    "freeAmountField18",
    "freeAmountField19",
    "freeAmountField20",
    "freeAmountField21",
    "freeAmountField22",
    "freeAmountField23",
    "freeAmountField24",
    "freeAmountField25",
    "freeAmountField26",
    "freeAmountField27",
    "freeAmountField28",
    "freeAmountField29",
    "freeAmountField30",
    "freeDateField01",
    "freeDateField02",
    "freeDateField03",
    "freeDateField04",
    "freeDateField05",
    "freeDateField06",
    "freeDateField07",
    "freeDateField08",
    "freeDateField09",
    "freeDateField10",
    "freeNoYesField01",
    "freeNoYesField02",
    "freeNoYesField03",
    "freeNoYesField04",
    "freeNoYesField05",
    "freeNoYesField06",
    "freeNoYesField07",
    "freeNoYesField08",
    "freeNoYesField09",
    "freeNoYesField10",
    "freeNoYesField11",
    "freeNoYesField12",
    "freeNoYesField13",
    "freeNoYesField14",
    "freeNoYesField15",
    "freeNoYesField16",
    "freeNoYesField17",
    "freeNoYesField18",
    "freeNoYesField19",
    "freeNoYesField20",
    "freeTextField01",
    "freeTextField02",
    "freeTextField03",
    "freeTextField04",
    "freeTextField05",
    "freeTextField06",
    "freeTextField07",
    "freeTextField08",
    "freeTextField09",
    "freeTextField10",
    "freeTextField11",
    "freeTextField12",
    "freeTextField13",
    "freeTextField14",
    "freeTextField15",
    "freeTextField16",
    "freeTextField17",
    "freeTextField18",
    "freeTextField19",
    "freeTextField20",
    "freeTextField21",
    "freeTextField22",
    "freeTextField23",
    "freeTextField24",
    "freeTextField25",
    "freeTextField26",
    "freeTextField27",
    "freeTextField28",
    "freeTextField29",
    "freeTextField30",
    "freeTextField31",
    "freeTextField32",
    "freeTextField33",
    "freeTextField34",
    "freeTextField35",
    "freeTextField36",
    "freeTextField37",
    "freeTextField38",
    "freeTextField39",
    "freeTextField40",
    "freeIntField01",
    "freeIntField02",
    "freeIntField03",
    "freeIntField04",
    "freeIntField05",
    "freeIntField06",
    "freeIntField07",
    "freeIntField08",
    "freeIntField09",
    "freeIntField10"
})
@XmlRootElement(name = "EmploymentAgencyTax")
public class EmploymentAgencyTax {

    @XmlElement(name = "PayrollYear")
    protected BigInteger payrollYear;
    @XmlElement(name = "Agency")
    protected Agency agency;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "FreeAmountField01")
    protected Float freeAmountField01;
    @XmlElement(name = "FreeAmountField02")
    protected Float freeAmountField02;
    @XmlElement(name = "FreeAmountField03")
    protected Float freeAmountField03;
    @XmlElement(name = "FreeAmountField04")
    protected Float freeAmountField04;
    @XmlElement(name = "FreeAmountField05")
    protected Float freeAmountField05;
    @XmlElement(name = "FreeAmountField06")
    protected Float freeAmountField06;
    @XmlElement(name = "FreeAmountField07")
    protected Float freeAmountField07;
    @XmlElement(name = "FreeAmountField08")
    protected Float freeAmountField08;
    @XmlElement(name = "FreeAmountField09")
    protected Float freeAmountField09;
    @XmlElement(name = "FreeAmountField10")
    protected Float freeAmountField10;
    @XmlElement(name = "FreeAmountField11")
    protected Float freeAmountField11;
    @XmlElement(name = "FreeAmountField12")
    protected Float freeAmountField12;
    @XmlElement(name = "FreeAmountField13")
    protected Float freeAmountField13;
    @XmlElement(name = "FreeAmountField14")
    protected Float freeAmountField14;
    @XmlElement(name = "FreeAmountField15")
    protected Float freeAmountField15;
    @XmlElement(name = "FreeAmountField16")
    protected Float freeAmountField16;
    @XmlElement(name = "FreeAmountField17")
    protected Float freeAmountField17;
    @XmlElement(name = "FreeAmountField18")
    protected Float freeAmountField18;
    @XmlElement(name = "FreeAmountField19")
    protected Float freeAmountField19;
    @XmlElement(name = "FreeAmountField20")
    protected Float freeAmountField20;
    @XmlElement(name = "FreeAmountField21")
    protected Float freeAmountField21;
    @XmlElement(name = "FreeAmountField22")
    protected Float freeAmountField22;
    @XmlElement(name = "FreeAmountField23")
    protected Float freeAmountField23;
    @XmlElement(name = "FreeAmountField24")
    protected Float freeAmountField24;
    @XmlElement(name = "FreeAmountField25")
    protected Float freeAmountField25;
    @XmlElement(name = "FreeAmountField26")
    protected Float freeAmountField26;
    @XmlElement(name = "FreeAmountField27")
    protected Float freeAmountField27;
    @XmlElement(name = "FreeAmountField28")
    protected Float freeAmountField28;
    @XmlElement(name = "FreeAmountField29")
    protected Float freeAmountField29;
    @XmlElement(name = "FreeAmountField30")
    protected Float freeAmountField30;
    @XmlElement(name = "FreeDateField01")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField01;
    @XmlElement(name = "FreeDateField02")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField02;
    @XmlElement(name = "FreeDateField03")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField03;
    @XmlElement(name = "FreeDateField04")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField04;
    @XmlElement(name = "FreeDateField05")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField05;
    @XmlElement(name = "FreeDateField06")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField06;
    @XmlElement(name = "FreeDateField07")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField07;
    @XmlElement(name = "FreeDateField08")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField08;
    @XmlElement(name = "FreeDateField09")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField09;
    @XmlElement(name = "FreeDateField10")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freeDateField10;
    @XmlElement(name = "FreeNoYesField01")
    protected Boolean freeNoYesField01;
    @XmlElement(name = "FreeNoYesField02")
    protected Boolean freeNoYesField02;
    @XmlElement(name = "FreeNoYesField03")
    protected Boolean freeNoYesField03;
    @XmlElement(name = "FreeNoYesField04")
    protected Boolean freeNoYesField04;
    @XmlElement(name = "FreeNoYesField05")
    protected Boolean freeNoYesField05;
    @XmlElement(name = "FreeNoYesField06")
    protected Boolean freeNoYesField06;
    @XmlElement(name = "FreeNoYesField07")
    protected Boolean freeNoYesField07;
    @XmlElement(name = "FreeNoYesField08")
    protected Boolean freeNoYesField08;
    @XmlElement(name = "FreeNoYesField09")
    protected Boolean freeNoYesField09;
    @XmlElement(name = "FreeNoYesField10")
    protected Boolean freeNoYesField10;
    @XmlElement(name = "FreeNoYesField11")
    protected Boolean freeNoYesField11;
    @XmlElement(name = "FreeNoYesField12")
    protected Boolean freeNoYesField12;
    @XmlElement(name = "FreeNoYesField13")
    protected Boolean freeNoYesField13;
    @XmlElement(name = "FreeNoYesField14")
    protected Boolean freeNoYesField14;
    @XmlElement(name = "FreeNoYesField15")
    protected Boolean freeNoYesField15;
    @XmlElement(name = "FreeNoYesField16")
    protected Boolean freeNoYesField16;
    @XmlElement(name = "FreeNoYesField17")
    protected Boolean freeNoYesField17;
    @XmlElement(name = "FreeNoYesField18")
    protected Boolean freeNoYesField18;
    @XmlElement(name = "FreeNoYesField19")
    protected Boolean freeNoYesField19;
    @XmlElement(name = "FreeNoYesField20")
    protected Boolean freeNoYesField20;
    @XmlElement(name = "FreeTextField01")
    protected String freeTextField01;
    @XmlElement(name = "FreeTextField02")
    protected String freeTextField02;
    @XmlElement(name = "FreeTextField03")
    protected String freeTextField03;
    @XmlElement(name = "FreeTextField04")
    protected String freeTextField04;
    @XmlElement(name = "FreeTextField05")
    protected String freeTextField05;
    @XmlElement(name = "FreeTextField06")
    protected String freeTextField06;
    @XmlElement(name = "FreeTextField07")
    protected String freeTextField07;
    @XmlElement(name = "FreeTextField08")
    protected String freeTextField08;
    @XmlElement(name = "FreeTextField09")
    protected String freeTextField09;
    @XmlElement(name = "FreeTextField10")
    protected String freeTextField10;
    @XmlElement(name = "FreeTextField11")
    protected String freeTextField11;
    @XmlElement(name = "FreeTextField12")
    protected String freeTextField12;
    @XmlElement(name = "FreeTextField13")
    protected String freeTextField13;
    @XmlElement(name = "FreeTextField14")
    protected String freeTextField14;
    @XmlElement(name = "FreeTextField15")
    protected String freeTextField15;
    @XmlElement(name = "FreeTextField16")
    protected String freeTextField16;
    @XmlElement(name = "FreeTextField17")
    protected String freeTextField17;
    @XmlElement(name = "FreeTextField18")
    protected String freeTextField18;
    @XmlElement(name = "FreeTextField19")
    protected String freeTextField19;
    @XmlElement(name = "FreeTextField20")
    protected String freeTextField20;
    @XmlElement(name = "FreeTextField21")
    protected String freeTextField21;
    @XmlElement(name = "FreeTextField22")
    protected String freeTextField22;
    @XmlElement(name = "FreeTextField23")
    protected String freeTextField23;
    @XmlElement(name = "FreeTextField24")
    protected String freeTextField24;
    @XmlElement(name = "FreeTextField25")
    protected String freeTextField25;
    @XmlElement(name = "FreeTextField26")
    protected String freeTextField26;
    @XmlElement(name = "FreeTextField27")
    protected String freeTextField27;
    @XmlElement(name = "FreeTextField28")
    protected String freeTextField28;
    @XmlElement(name = "FreeTextField29")
    protected String freeTextField29;
    @XmlElement(name = "FreeTextField30")
    protected String freeTextField30;
    @XmlElement(name = "FreeTextField31")
    protected String freeTextField31;
    @XmlElement(name = "FreeTextField32")
    protected String freeTextField32;
    @XmlElement(name = "FreeTextField33")
    protected String freeTextField33;
    @XmlElement(name = "FreeTextField34")
    protected String freeTextField34;
    @XmlElement(name = "FreeTextField35")
    protected String freeTextField35;
    @XmlElement(name = "FreeTextField36")
    protected String freeTextField36;
    @XmlElement(name = "FreeTextField37")
    protected String freeTextField37;
    @XmlElement(name = "FreeTextField38")
    protected String freeTextField38;
    @XmlElement(name = "FreeTextField39")
    protected String freeTextField39;
    @XmlElement(name = "FreeTextField40")
    protected String freeTextField40;
    @XmlElement(name = "FreeIntField01")
    protected BigInteger freeIntField01;
    @XmlElement(name = "FreeIntField02")
    protected BigInteger freeIntField02;
    @XmlElement(name = "FreeIntField03")
    protected BigInteger freeIntField03;
    @XmlElement(name = "FreeIntField04")
    protected BigInteger freeIntField04;
    @XmlElement(name = "FreeIntField05")
    protected BigInteger freeIntField05;
    @XmlElement(name = "FreeIntField06")
    protected BigInteger freeIntField06;
    @XmlElement(name = "FreeIntField07")
    protected BigInteger freeIntField07;
    @XmlElement(name = "FreeIntField08")
    protected BigInteger freeIntField08;
    @XmlElement(name = "FreeIntField09")
    protected BigInteger freeIntField09;
    @XmlElement(name = "FreeIntField10")
    protected BigInteger freeIntField10;

    /**
     * Gets the value of the payrollYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayrollYear() {
        return payrollYear;
    }

    /**
     * Sets the value of the payrollYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayrollYear(BigInteger value) {
        this.payrollYear = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link Agency }
     *     
     */
    public Agency getAgency() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agency }
     *     
     */
    public void setAgency(Agency value) {
        this.agency = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the freeAmountField01 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField01() {
        return freeAmountField01;
    }

    /**
     * Sets the value of the freeAmountField01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField01(Float value) {
        this.freeAmountField01 = value;
    }

    /**
     * Gets the value of the freeAmountField02 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField02() {
        return freeAmountField02;
    }

    /**
     * Sets the value of the freeAmountField02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField02(Float value) {
        this.freeAmountField02 = value;
    }

    /**
     * Gets the value of the freeAmountField03 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField03() {
        return freeAmountField03;
    }

    /**
     * Sets the value of the freeAmountField03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField03(Float value) {
        this.freeAmountField03 = value;
    }

    /**
     * Gets the value of the freeAmountField04 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField04() {
        return freeAmountField04;
    }

    /**
     * Sets the value of the freeAmountField04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField04(Float value) {
        this.freeAmountField04 = value;
    }

    /**
     * Gets the value of the freeAmountField05 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField05() {
        return freeAmountField05;
    }

    /**
     * Sets the value of the freeAmountField05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField05(Float value) {
        this.freeAmountField05 = value;
    }

    /**
     * Gets the value of the freeAmountField06 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField06() {
        return freeAmountField06;
    }

    /**
     * Sets the value of the freeAmountField06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField06(Float value) {
        this.freeAmountField06 = value;
    }

    /**
     * Gets the value of the freeAmountField07 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField07() {
        return freeAmountField07;
    }

    /**
     * Sets the value of the freeAmountField07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField07(Float value) {
        this.freeAmountField07 = value;
    }

    /**
     * Gets the value of the freeAmountField08 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField08() {
        return freeAmountField08;
    }

    /**
     * Sets the value of the freeAmountField08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField08(Float value) {
        this.freeAmountField08 = value;
    }

    /**
     * Gets the value of the freeAmountField09 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField09() {
        return freeAmountField09;
    }

    /**
     * Sets the value of the freeAmountField09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField09(Float value) {
        this.freeAmountField09 = value;
    }

    /**
     * Gets the value of the freeAmountField10 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField10() {
        return freeAmountField10;
    }

    /**
     * Sets the value of the freeAmountField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField10(Float value) {
        this.freeAmountField10 = value;
    }

    /**
     * Gets the value of the freeAmountField11 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField11() {
        return freeAmountField11;
    }

    /**
     * Sets the value of the freeAmountField11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField11(Float value) {
        this.freeAmountField11 = value;
    }

    /**
     * Gets the value of the freeAmountField12 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField12() {
        return freeAmountField12;
    }

    /**
     * Sets the value of the freeAmountField12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField12(Float value) {
        this.freeAmountField12 = value;
    }

    /**
     * Gets the value of the freeAmountField13 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField13() {
        return freeAmountField13;
    }

    /**
     * Sets the value of the freeAmountField13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField13(Float value) {
        this.freeAmountField13 = value;
    }

    /**
     * Gets the value of the freeAmountField14 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField14() {
        return freeAmountField14;
    }

    /**
     * Sets the value of the freeAmountField14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField14(Float value) {
        this.freeAmountField14 = value;
    }

    /**
     * Gets the value of the freeAmountField15 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField15() {
        return freeAmountField15;
    }

    /**
     * Sets the value of the freeAmountField15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField15(Float value) {
        this.freeAmountField15 = value;
    }

    /**
     * Gets the value of the freeAmountField16 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField16() {
        return freeAmountField16;
    }

    /**
     * Sets the value of the freeAmountField16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField16(Float value) {
        this.freeAmountField16 = value;
    }

    /**
     * Gets the value of the freeAmountField17 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField17() {
        return freeAmountField17;
    }

    /**
     * Sets the value of the freeAmountField17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField17(Float value) {
        this.freeAmountField17 = value;
    }

    /**
     * Gets the value of the freeAmountField18 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField18() {
        return freeAmountField18;
    }

    /**
     * Sets the value of the freeAmountField18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField18(Float value) {
        this.freeAmountField18 = value;
    }

    /**
     * Gets the value of the freeAmountField19 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField19() {
        return freeAmountField19;
    }

    /**
     * Sets the value of the freeAmountField19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField19(Float value) {
        this.freeAmountField19 = value;
    }

    /**
     * Gets the value of the freeAmountField20 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField20() {
        return freeAmountField20;
    }

    /**
     * Sets the value of the freeAmountField20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField20(Float value) {
        this.freeAmountField20 = value;
    }

    /**
     * Gets the value of the freeAmountField21 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField21() {
        return freeAmountField21;
    }

    /**
     * Sets the value of the freeAmountField21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField21(Float value) {
        this.freeAmountField21 = value;
    }

    /**
     * Gets the value of the freeAmountField22 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField22() {
        return freeAmountField22;
    }

    /**
     * Sets the value of the freeAmountField22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField22(Float value) {
        this.freeAmountField22 = value;
    }

    /**
     * Gets the value of the freeAmountField23 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField23() {
        return freeAmountField23;
    }

    /**
     * Sets the value of the freeAmountField23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField23(Float value) {
        this.freeAmountField23 = value;
    }

    /**
     * Gets the value of the freeAmountField24 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField24() {
        return freeAmountField24;
    }

    /**
     * Sets the value of the freeAmountField24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField24(Float value) {
        this.freeAmountField24 = value;
    }

    /**
     * Gets the value of the freeAmountField25 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField25() {
        return freeAmountField25;
    }

    /**
     * Sets the value of the freeAmountField25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField25(Float value) {
        this.freeAmountField25 = value;
    }

    /**
     * Gets the value of the freeAmountField26 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField26() {
        return freeAmountField26;
    }

    /**
     * Sets the value of the freeAmountField26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField26(Float value) {
        this.freeAmountField26 = value;
    }

    /**
     * Gets the value of the freeAmountField27 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField27() {
        return freeAmountField27;
    }

    /**
     * Sets the value of the freeAmountField27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField27(Float value) {
        this.freeAmountField27 = value;
    }

    /**
     * Gets the value of the freeAmountField28 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField28() {
        return freeAmountField28;
    }

    /**
     * Sets the value of the freeAmountField28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField28(Float value) {
        this.freeAmountField28 = value;
    }

    /**
     * Gets the value of the freeAmountField29 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField29() {
        return freeAmountField29;
    }

    /**
     * Sets the value of the freeAmountField29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField29(Float value) {
        this.freeAmountField29 = value;
    }

    /**
     * Gets the value of the freeAmountField30 property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFreeAmountField30() {
        return freeAmountField30;
    }

    /**
     * Sets the value of the freeAmountField30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFreeAmountField30(Float value) {
        this.freeAmountField30 = value;
    }

    /**
     * Gets the value of the freeDateField01 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField01() {
        return freeDateField01;
    }

    /**
     * Sets the value of the freeDateField01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField01(XMLGregorianCalendar value) {
        this.freeDateField01 = value;
    }

    /**
     * Gets the value of the freeDateField02 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField02() {
        return freeDateField02;
    }

    /**
     * Sets the value of the freeDateField02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField02(XMLGregorianCalendar value) {
        this.freeDateField02 = value;
    }

    /**
     * Gets the value of the freeDateField03 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField03() {
        return freeDateField03;
    }

    /**
     * Sets the value of the freeDateField03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField03(XMLGregorianCalendar value) {
        this.freeDateField03 = value;
    }

    /**
     * Gets the value of the freeDateField04 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField04() {
        return freeDateField04;
    }

    /**
     * Sets the value of the freeDateField04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField04(XMLGregorianCalendar value) {
        this.freeDateField04 = value;
    }

    /**
     * Gets the value of the freeDateField05 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField05() {
        return freeDateField05;
    }

    /**
     * Sets the value of the freeDateField05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField05(XMLGregorianCalendar value) {
        this.freeDateField05 = value;
    }

    /**
     * Gets the value of the freeDateField06 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField06() {
        return freeDateField06;
    }

    /**
     * Sets the value of the freeDateField06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField06(XMLGregorianCalendar value) {
        this.freeDateField06 = value;
    }

    /**
     * Gets the value of the freeDateField07 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField07() {
        return freeDateField07;
    }

    /**
     * Sets the value of the freeDateField07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField07(XMLGregorianCalendar value) {
        this.freeDateField07 = value;
    }

    /**
     * Gets the value of the freeDateField08 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField08() {
        return freeDateField08;
    }

    /**
     * Sets the value of the freeDateField08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField08(XMLGregorianCalendar value) {
        this.freeDateField08 = value;
    }

    /**
     * Gets the value of the freeDateField09 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField09() {
        return freeDateField09;
    }

    /**
     * Sets the value of the freeDateField09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField09(XMLGregorianCalendar value) {
        this.freeDateField09 = value;
    }

    /**
     * Gets the value of the freeDateField10 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreeDateField10() {
        return freeDateField10;
    }

    /**
     * Sets the value of the freeDateField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreeDateField10(XMLGregorianCalendar value) {
        this.freeDateField10 = value;
    }

    /**
     * Gets the value of the freeNoYesField01 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField01() {
        return freeNoYesField01;
    }

    /**
     * Sets the value of the freeNoYesField01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField01(Boolean value) {
        this.freeNoYesField01 = value;
    }

    /**
     * Gets the value of the freeNoYesField02 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField02() {
        return freeNoYesField02;
    }

    /**
     * Sets the value of the freeNoYesField02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField02(Boolean value) {
        this.freeNoYesField02 = value;
    }

    /**
     * Gets the value of the freeNoYesField03 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField03() {
        return freeNoYesField03;
    }

    /**
     * Sets the value of the freeNoYesField03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField03(Boolean value) {
        this.freeNoYesField03 = value;
    }

    /**
     * Gets the value of the freeNoYesField04 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField04() {
        return freeNoYesField04;
    }

    /**
     * Sets the value of the freeNoYesField04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField04(Boolean value) {
        this.freeNoYesField04 = value;
    }

    /**
     * Gets the value of the freeNoYesField05 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField05() {
        return freeNoYesField05;
    }

    /**
     * Sets the value of the freeNoYesField05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField05(Boolean value) {
        this.freeNoYesField05 = value;
    }

    /**
     * Gets the value of the freeNoYesField06 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField06() {
        return freeNoYesField06;
    }

    /**
     * Sets the value of the freeNoYesField06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField06(Boolean value) {
        this.freeNoYesField06 = value;
    }

    /**
     * Gets the value of the freeNoYesField07 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField07() {
        return freeNoYesField07;
    }

    /**
     * Sets the value of the freeNoYesField07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField07(Boolean value) {
        this.freeNoYesField07 = value;
    }

    /**
     * Gets the value of the freeNoYesField08 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField08() {
        return freeNoYesField08;
    }

    /**
     * Sets the value of the freeNoYesField08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField08(Boolean value) {
        this.freeNoYesField08 = value;
    }

    /**
     * Gets the value of the freeNoYesField09 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField09() {
        return freeNoYesField09;
    }

    /**
     * Sets the value of the freeNoYesField09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField09(Boolean value) {
        this.freeNoYesField09 = value;
    }

    /**
     * Gets the value of the freeNoYesField10 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField10() {
        return freeNoYesField10;
    }

    /**
     * Sets the value of the freeNoYesField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField10(Boolean value) {
        this.freeNoYesField10 = value;
    }

    /**
     * Gets the value of the freeNoYesField11 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField11() {
        return freeNoYesField11;
    }

    /**
     * Sets the value of the freeNoYesField11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField11(Boolean value) {
        this.freeNoYesField11 = value;
    }

    /**
     * Gets the value of the freeNoYesField12 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField12() {
        return freeNoYesField12;
    }

    /**
     * Sets the value of the freeNoYesField12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField12(Boolean value) {
        this.freeNoYesField12 = value;
    }

    /**
     * Gets the value of the freeNoYesField13 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField13() {
        return freeNoYesField13;
    }

    /**
     * Sets the value of the freeNoYesField13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField13(Boolean value) {
        this.freeNoYesField13 = value;
    }

    /**
     * Gets the value of the freeNoYesField14 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField14() {
        return freeNoYesField14;
    }

    /**
     * Sets the value of the freeNoYesField14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField14(Boolean value) {
        this.freeNoYesField14 = value;
    }

    /**
     * Gets the value of the freeNoYesField15 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField15() {
        return freeNoYesField15;
    }

    /**
     * Sets the value of the freeNoYesField15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField15(Boolean value) {
        this.freeNoYesField15 = value;
    }

    /**
     * Gets the value of the freeNoYesField16 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField16() {
        return freeNoYesField16;
    }

    /**
     * Sets the value of the freeNoYesField16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField16(Boolean value) {
        this.freeNoYesField16 = value;
    }

    /**
     * Gets the value of the freeNoYesField17 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField17() {
        return freeNoYesField17;
    }

    /**
     * Sets the value of the freeNoYesField17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField17(Boolean value) {
        this.freeNoYesField17 = value;
    }

    /**
     * Gets the value of the freeNoYesField18 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField18() {
        return freeNoYesField18;
    }

    /**
     * Sets the value of the freeNoYesField18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField18(Boolean value) {
        this.freeNoYesField18 = value;
    }

    /**
     * Gets the value of the freeNoYesField19 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField19() {
        return freeNoYesField19;
    }

    /**
     * Sets the value of the freeNoYesField19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField19(Boolean value) {
        this.freeNoYesField19 = value;
    }

    /**
     * Gets the value of the freeNoYesField20 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreeNoYesField20() {
        return freeNoYesField20;
    }

    /**
     * Sets the value of the freeNoYesField20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreeNoYesField20(Boolean value) {
        this.freeNoYesField20 = value;
    }

    /**
     * Gets the value of the freeTextField01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField01() {
        return freeTextField01;
    }

    /**
     * Sets the value of the freeTextField01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField01(String value) {
        this.freeTextField01 = value;
    }

    /**
     * Gets the value of the freeTextField02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField02() {
        return freeTextField02;
    }

    /**
     * Sets the value of the freeTextField02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField02(String value) {
        this.freeTextField02 = value;
    }

    /**
     * Gets the value of the freeTextField03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField03() {
        return freeTextField03;
    }

    /**
     * Sets the value of the freeTextField03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField03(String value) {
        this.freeTextField03 = value;
    }

    /**
     * Gets the value of the freeTextField04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField04() {
        return freeTextField04;
    }

    /**
     * Sets the value of the freeTextField04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField04(String value) {
        this.freeTextField04 = value;
    }

    /**
     * Gets the value of the freeTextField05 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField05() {
        return freeTextField05;
    }

    /**
     * Sets the value of the freeTextField05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField05(String value) {
        this.freeTextField05 = value;
    }

    /**
     * Gets the value of the freeTextField06 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField06() {
        return freeTextField06;
    }

    /**
     * Sets the value of the freeTextField06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField06(String value) {
        this.freeTextField06 = value;
    }

    /**
     * Gets the value of the freeTextField07 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField07() {
        return freeTextField07;
    }

    /**
     * Sets the value of the freeTextField07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField07(String value) {
        this.freeTextField07 = value;
    }

    /**
     * Gets the value of the freeTextField08 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField08() {
        return freeTextField08;
    }

    /**
     * Sets the value of the freeTextField08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField08(String value) {
        this.freeTextField08 = value;
    }

    /**
     * Gets the value of the freeTextField09 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField09() {
        return freeTextField09;
    }

    /**
     * Sets the value of the freeTextField09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField09(String value) {
        this.freeTextField09 = value;
    }

    /**
     * Gets the value of the freeTextField10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField10() {
        return freeTextField10;
    }

    /**
     * Sets the value of the freeTextField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField10(String value) {
        this.freeTextField10 = value;
    }

    /**
     * Gets the value of the freeTextField11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField11() {
        return freeTextField11;
    }

    /**
     * Sets the value of the freeTextField11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField11(String value) {
        this.freeTextField11 = value;
    }

    /**
     * Gets the value of the freeTextField12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField12() {
        return freeTextField12;
    }

    /**
     * Sets the value of the freeTextField12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField12(String value) {
        this.freeTextField12 = value;
    }

    /**
     * Gets the value of the freeTextField13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField13() {
        return freeTextField13;
    }

    /**
     * Sets the value of the freeTextField13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField13(String value) {
        this.freeTextField13 = value;
    }

    /**
     * Gets the value of the freeTextField14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField14() {
        return freeTextField14;
    }

    /**
     * Sets the value of the freeTextField14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField14(String value) {
        this.freeTextField14 = value;
    }

    /**
     * Gets the value of the freeTextField15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField15() {
        return freeTextField15;
    }

    /**
     * Sets the value of the freeTextField15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField15(String value) {
        this.freeTextField15 = value;
    }

    /**
     * Gets the value of the freeTextField16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField16() {
        return freeTextField16;
    }

    /**
     * Sets the value of the freeTextField16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField16(String value) {
        this.freeTextField16 = value;
    }

    /**
     * Gets the value of the freeTextField17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField17() {
        return freeTextField17;
    }

    /**
     * Sets the value of the freeTextField17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField17(String value) {
        this.freeTextField17 = value;
    }

    /**
     * Gets the value of the freeTextField18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField18() {
        return freeTextField18;
    }

    /**
     * Sets the value of the freeTextField18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField18(String value) {
        this.freeTextField18 = value;
    }

    /**
     * Gets the value of the freeTextField19 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField19() {
        return freeTextField19;
    }

    /**
     * Sets the value of the freeTextField19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField19(String value) {
        this.freeTextField19 = value;
    }

    /**
     * Gets the value of the freeTextField20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField20() {
        return freeTextField20;
    }

    /**
     * Sets the value of the freeTextField20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField20(String value) {
        this.freeTextField20 = value;
    }

    /**
     * Gets the value of the freeTextField21 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField21() {
        return freeTextField21;
    }

    /**
     * Sets the value of the freeTextField21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField21(String value) {
        this.freeTextField21 = value;
    }

    /**
     * Gets the value of the freeTextField22 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField22() {
        return freeTextField22;
    }

    /**
     * Sets the value of the freeTextField22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField22(String value) {
        this.freeTextField22 = value;
    }

    /**
     * Gets the value of the freeTextField23 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField23() {
        return freeTextField23;
    }

    /**
     * Sets the value of the freeTextField23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField23(String value) {
        this.freeTextField23 = value;
    }

    /**
     * Gets the value of the freeTextField24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField24() {
        return freeTextField24;
    }

    /**
     * Sets the value of the freeTextField24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField24(String value) {
        this.freeTextField24 = value;
    }

    /**
     * Gets the value of the freeTextField25 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField25() {
        return freeTextField25;
    }

    /**
     * Sets the value of the freeTextField25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField25(String value) {
        this.freeTextField25 = value;
    }

    /**
     * Gets the value of the freeTextField26 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField26() {
        return freeTextField26;
    }

    /**
     * Sets the value of the freeTextField26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField26(String value) {
        this.freeTextField26 = value;
    }

    /**
     * Gets the value of the freeTextField27 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField27() {
        return freeTextField27;
    }

    /**
     * Sets the value of the freeTextField27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField27(String value) {
        this.freeTextField27 = value;
    }

    /**
     * Gets the value of the freeTextField28 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField28() {
        return freeTextField28;
    }

    /**
     * Sets the value of the freeTextField28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField28(String value) {
        this.freeTextField28 = value;
    }

    /**
     * Gets the value of the freeTextField29 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField29() {
        return freeTextField29;
    }

    /**
     * Sets the value of the freeTextField29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField29(String value) {
        this.freeTextField29 = value;
    }

    /**
     * Gets the value of the freeTextField30 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField30() {
        return freeTextField30;
    }

    /**
     * Sets the value of the freeTextField30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField30(String value) {
        this.freeTextField30 = value;
    }

    /**
     * Gets the value of the freeTextField31 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField31() {
        return freeTextField31;
    }

    /**
     * Sets the value of the freeTextField31 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField31(String value) {
        this.freeTextField31 = value;
    }

    /**
     * Gets the value of the freeTextField32 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField32() {
        return freeTextField32;
    }

    /**
     * Sets the value of the freeTextField32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField32(String value) {
        this.freeTextField32 = value;
    }

    /**
     * Gets the value of the freeTextField33 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField33() {
        return freeTextField33;
    }

    /**
     * Sets the value of the freeTextField33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField33(String value) {
        this.freeTextField33 = value;
    }

    /**
     * Gets the value of the freeTextField34 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField34() {
        return freeTextField34;
    }

    /**
     * Sets the value of the freeTextField34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField34(String value) {
        this.freeTextField34 = value;
    }

    /**
     * Gets the value of the freeTextField35 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField35() {
        return freeTextField35;
    }

    /**
     * Sets the value of the freeTextField35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField35(String value) {
        this.freeTextField35 = value;
    }

    /**
     * Gets the value of the freeTextField36 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField36() {
        return freeTextField36;
    }

    /**
     * Sets the value of the freeTextField36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField36(String value) {
        this.freeTextField36 = value;
    }

    /**
     * Gets the value of the freeTextField37 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField37() {
        return freeTextField37;
    }

    /**
     * Sets the value of the freeTextField37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField37(String value) {
        this.freeTextField37 = value;
    }

    /**
     * Gets the value of the freeTextField38 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField38() {
        return freeTextField38;
    }

    /**
     * Sets the value of the freeTextField38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField38(String value) {
        this.freeTextField38 = value;
    }

    /**
     * Gets the value of the freeTextField39 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField39() {
        return freeTextField39;
    }

    /**
     * Sets the value of the freeTextField39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField39(String value) {
        this.freeTextField39 = value;
    }

    /**
     * Gets the value of the freeTextField40 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeTextField40() {
        return freeTextField40;
    }

    /**
     * Sets the value of the freeTextField40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeTextField40(String value) {
        this.freeTextField40 = value;
    }

    /**
     * Gets the value of the freeIntField01 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField01() {
        return freeIntField01;
    }

    /**
     * Sets the value of the freeIntField01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField01(BigInteger value) {
        this.freeIntField01 = value;
    }

    /**
     * Gets the value of the freeIntField02 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField02() {
        return freeIntField02;
    }

    /**
     * Sets the value of the freeIntField02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField02(BigInteger value) {
        this.freeIntField02 = value;
    }

    /**
     * Gets the value of the freeIntField03 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField03() {
        return freeIntField03;
    }

    /**
     * Sets the value of the freeIntField03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField03(BigInteger value) {
        this.freeIntField03 = value;
    }

    /**
     * Gets the value of the freeIntField04 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField04() {
        return freeIntField04;
    }

    /**
     * Sets the value of the freeIntField04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField04(BigInteger value) {
        this.freeIntField04 = value;
    }

    /**
     * Gets the value of the freeIntField05 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField05() {
        return freeIntField05;
    }

    /**
     * Sets the value of the freeIntField05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField05(BigInteger value) {
        this.freeIntField05 = value;
    }

    /**
     * Gets the value of the freeIntField06 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField06() {
        return freeIntField06;
    }

    /**
     * Sets the value of the freeIntField06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField06(BigInteger value) {
        this.freeIntField06 = value;
    }

    /**
     * Gets the value of the freeIntField07 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField07() {
        return freeIntField07;
    }

    /**
     * Sets the value of the freeIntField07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField07(BigInteger value) {
        this.freeIntField07 = value;
    }

    /**
     * Gets the value of the freeIntField08 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField08() {
        return freeIntField08;
    }

    /**
     * Sets the value of the freeIntField08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField08(BigInteger value) {
        this.freeIntField08 = value;
    }

    /**
     * Gets the value of the freeIntField09 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField09() {
        return freeIntField09;
    }

    /**
     * Sets the value of the freeIntField09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField09(BigInteger value) {
        this.freeIntField09 = value;
    }

    /**
     * Gets the value of the freeIntField10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeIntField10() {
        return freeIntField10;
    }

    /**
     * Sets the value of the freeIntField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeIntField10(BigInteger value) {
        this.freeIntField10 = value;
    }

}
