//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="NickName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressStreet" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressStreetNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressStreetNumberSuffix" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StreetNumberLocation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StreetNumberIndication" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressPostcode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressCity" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Profession" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="YearsOfEducation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Graduated" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="GraduationYear" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="EducationalOrganization" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="EducationalOrganizationLocation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CountryOfBirth" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}Education" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="HID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nickName",
    "firstName",
    "middleName",
    "lastName",
    "fullName",
    "addressStreet",
    "addressStreetNumber",
    "addressStreetNumberSuffix",
    "streetNumberLocation",
    "streetNumberIndication",
    "addressPostcode",
    "addressCity",
    "phone",
    "birthDate",
    "gender",
    "nationality",
    "profession",
    "yearsOfEducation",
    "graduated",
    "graduationYear",
    "educationalOrganization",
    "educationalOrganizationLocation",
    "countryOfBirth",
    "education"
})
@XmlRootElement(name = "Parent")
public class Parent {

    @XmlElement(name = "NickName")
    protected Object nickName;
    @XmlElement(name = "FirstName")
    protected Object firstName;
    @XmlElement(name = "MiddleName")
    protected Object middleName;
    @XmlElement(name = "LastName")
    protected Object lastName;
    @XmlElement(name = "FullName")
    protected Object fullName;
    @XmlElement(name = "AddressStreet")
    protected Object addressStreet;
    @XmlElement(name = "AddressStreetNumber")
    protected Object addressStreetNumber;
    @XmlElement(name = "AddressStreetNumberSuffix")
    protected Object addressStreetNumberSuffix;
    @XmlElement(name = "StreetNumberLocation")
    protected Object streetNumberLocation;
    @XmlElement(name = "StreetNumberIndication")
    protected Object streetNumberIndication;
    @XmlElement(name = "AddressPostcode")
    protected Object addressPostcode;
    @XmlElement(name = "AddressCity")
    protected Object addressCity;
    @XmlElement(name = "Phone")
    protected Object phone;
    @XmlElement(name = "BirthDate")
    protected Object birthDate;
    @XmlElement(name = "Gender")
    protected Object gender;
    @XmlElement(name = "Nationality")
    protected Object nationality;
    @XmlElement(name = "Profession")
    protected Object profession;
    @XmlElement(name = "YearsOfEducation")
    protected Object yearsOfEducation;
    @XmlElement(name = "Graduated")
    protected Object graduated;
    @XmlElement(name = "GraduationYear")
    protected Object graduationYear;
    @XmlElement(name = "EducationalOrganization")
    protected Object educationalOrganization;
    @XmlElement(name = "EducationalOrganizationLocation")
    protected Object educationalOrganizationLocation;
    @XmlElement(name = "CountryOfBirth")
    protected Object countryOfBirth;
    @XmlElement(name = "Education")
    protected Education education;
    @XmlAttribute(name = "HID", required = true)
    protected String hid;

    /**
     * Gets the value of the nickName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNickName() {
        return nickName;
    }

    /**
     * Sets the value of the nickName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNickName(Object value) {
        this.nickName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFirstName(Object value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMiddleName(Object value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLastName(Object value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFullName(Object value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the addressStreet property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressStreet() {
        return addressStreet;
    }

    /**
     * Sets the value of the addressStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressStreet(Object value) {
        this.addressStreet = value;
    }

    /**
     * Gets the value of the addressStreetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressStreetNumber() {
        return addressStreetNumber;
    }

    /**
     * Sets the value of the addressStreetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressStreetNumber(Object value) {
        this.addressStreetNumber = value;
    }

    /**
     * Gets the value of the addressStreetNumberSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressStreetNumberSuffix() {
        return addressStreetNumberSuffix;
    }

    /**
     * Sets the value of the addressStreetNumberSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressStreetNumberSuffix(Object value) {
        this.addressStreetNumberSuffix = value;
    }

    /**
     * Gets the value of the streetNumberLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStreetNumberLocation() {
        return streetNumberLocation;
    }

    /**
     * Sets the value of the streetNumberLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStreetNumberLocation(Object value) {
        this.streetNumberLocation = value;
    }

    /**
     * Gets the value of the streetNumberIndication property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStreetNumberIndication() {
        return streetNumberIndication;
    }

    /**
     * Sets the value of the streetNumberIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStreetNumberIndication(Object value) {
        this.streetNumberIndication = value;
    }

    /**
     * Gets the value of the addressPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressPostcode() {
        return addressPostcode;
    }

    /**
     * Sets the value of the addressPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressPostcode(Object value) {
        this.addressPostcode = value;
    }

    /**
     * Gets the value of the addressCity property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressCity() {
        return addressCity;
    }

    /**
     * Sets the value of the addressCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressCity(Object value) {
        this.addressCity = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPhone(Object value) {
        this.phone = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBirthDate(Object value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGender(Object value) {
        this.gender = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNationality(Object value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProfession() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProfession(Object value) {
        this.profession = value;
    }

    /**
     * Gets the value of the yearsOfEducation property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getYearsOfEducation() {
        return yearsOfEducation;
    }

    /**
     * Sets the value of the yearsOfEducation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setYearsOfEducation(Object value) {
        this.yearsOfEducation = value;
    }

    /**
     * Gets the value of the graduated property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGraduated() {
        return graduated;
    }

    /**
     * Sets the value of the graduated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGraduated(Object value) {
        this.graduated = value;
    }

    /**
     * Gets the value of the graduationYear property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGraduationYear() {
        return graduationYear;
    }

    /**
     * Sets the value of the graduationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGraduationYear(Object value) {
        this.graduationYear = value;
    }

    /**
     * Gets the value of the educationalOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEducationalOrganization() {
        return educationalOrganization;
    }

    /**
     * Sets the value of the educationalOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEducationalOrganization(Object value) {
        this.educationalOrganization = value;
    }

    /**
     * Gets the value of the educationalOrganizationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEducationalOrganizationLocation() {
        return educationalOrganizationLocation;
    }

    /**
     * Sets the value of the educationalOrganizationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEducationalOrganizationLocation(Object value) {
        this.educationalOrganizationLocation = value;
    }

    /**
     * Gets the value of the countryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCountryOfBirth(Object value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link Education }
     *     
     */
    public Education getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link Education }
     *     
     */
    public void setEducation(Education value) {
        this.education = value;
    }

    /**
     * Gets the value of the hid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHID() {
        return hid;
    }

    /**
     * Sets the value of the hid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHID(String value) {
        this.hid = value;
    }

}
