//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="StudentState" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="NickName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressStreet" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressStreetNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AddressStreetNumberSuffix" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StreetNumberLocation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StreetNumberIndication" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Postcode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CountryOfBirth" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SocialSecurityNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="EducationalNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FirstDayAtSchool" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FirstLessonDate" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="DateOfDeregistration" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="TransportType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="HealthInsuranceNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SecondNationality" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="VOAdvice" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="PreSchoolProgram" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SchoolType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StartDateSchoolType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="EducationalType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StartDateEducationalType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Residential" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Accompaniment" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StartDateTrainingPeriode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="EndDateTrainingPeriode" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SchoolDrink" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ParentStatus" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="TypeOfStay" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="DateTypeOfStay" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="PGNStudentNumber" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="BRON" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StartDateDidacticAge" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SchoolCareers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}SchoolCareer" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StudentHandicaps" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}StudentHandicap" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StudentRelations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}StudentRelation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Denomination" minOccurs="0"/>
 *         &lt;element name="TransportCompany" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Account"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GeneralPractioner" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Account"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExtraMedicalAccount" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Account"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TrainingPeriodCompany" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Account"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}ID"/>
 *       &lt;attribute ref="{}code use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "studentState",
    "nickName",
    "firstName",
    "middleName",
    "lastName",
    "fullName",
    "addressStreet",
    "addressStreetNumber",
    "addressStreetNumberSuffix",
    "streetNumberLocation",
    "streetNumberIndication",
    "postcode",
    "city",
    "phone",
    "birthDate",
    "gender",
    "countryOfBirth",
    "nationality",
    "socialSecurityNumber",
    "educationalNumber",
    "firstDayAtSchool",
    "firstLessonDate",
    "dateOfDeregistration",
    "transportType",
    "healthInsuranceNumber",
    "secondNationality",
    "voAdvice",
    "preSchoolProgram",
    "schoolType",
    "startDateSchoolType",
    "educationalType",
    "startDateEducationalType",
    "residential",
    "accompaniment",
    "startDateTrainingPeriode",
    "endDateTrainingPeriode",
    "schoolDrink",
    "parentStatus",
    "typeOfStay",
    "dateTypeOfStay",
    "pgnStudentNumber",
    "bron",
    "startDateDidacticAge",
    "schoolCareers",
    "studentHandicaps",
    "studentRelations",
    "denomination",
    "transportCompany",
    "generalPractioner",
    "extraMedicalAccount",
    "trainingPeriodCompany"
})
@XmlRootElement(name = "Student")
public class Student {

    @XmlElement(name = "StudentState")
    protected Object studentState;
    @XmlElement(name = "NickName")
    protected Object nickName;
    @XmlElement(name = "FirstName")
    protected Object firstName;
    @XmlElement(name = "MiddleName")
    protected Object middleName;
    @XmlElement(name = "LastName")
    protected Object lastName;
    @XmlElement(name = "FullName")
    protected Object fullName;
    @XmlElement(name = "AddressStreet")
    protected Object addressStreet;
    @XmlElement(name = "AddressStreetNumber")
    protected Object addressStreetNumber;
    @XmlElement(name = "AddressStreetNumberSuffix")
    protected Object addressStreetNumberSuffix;
    @XmlElement(name = "StreetNumberLocation")
    protected Object streetNumberLocation;
    @XmlElement(name = "StreetNumberIndication")
    protected Object streetNumberIndication;
    @XmlElement(name = "Postcode")
    protected Object postcode;
    @XmlElement(name = "City")
    protected Object city;
    @XmlElement(name = "Phone")
    protected Object phone;
    @XmlElement(name = "BirthDate")
    protected Object birthDate;
    @XmlElement(name = "Gender")
    protected Object gender;
    @XmlElement(name = "CountryOfBirth")
    protected Object countryOfBirth;
    @XmlElement(name = "Nationality")
    protected Object nationality;
    @XmlElement(name = "SocialSecurityNumber")
    protected Object socialSecurityNumber;
    @XmlElement(name = "EducationalNumber")
    protected Object educationalNumber;
    @XmlElement(name = "FirstDayAtSchool")
    protected Object firstDayAtSchool;
    @XmlElement(name = "FirstLessonDate")
    protected Object firstLessonDate;
    @XmlElement(name = "DateOfDeregistration")
    protected Object dateOfDeregistration;
    @XmlElement(name = "TransportType")
    protected Object transportType;
    @XmlElement(name = "HealthInsuranceNumber")
    protected Object healthInsuranceNumber;
    @XmlElement(name = "SecondNationality")
    protected Object secondNationality;
    @XmlElement(name = "VOAdvice")
    protected Object voAdvice;
    @XmlElement(name = "PreSchoolProgram")
    protected Object preSchoolProgram;
    @XmlElement(name = "SchoolType")
    protected Object schoolType;
    @XmlElement(name = "StartDateSchoolType")
    protected Object startDateSchoolType;
    @XmlElement(name = "EducationalType")
    protected Object educationalType;
    @XmlElement(name = "StartDateEducationalType")
    protected Object startDateEducationalType;
    @XmlElement(name = "Residential")
    protected Object residential;
    @XmlElement(name = "Accompaniment")
    protected Object accompaniment;
    @XmlElement(name = "StartDateTrainingPeriode")
    protected Object startDateTrainingPeriode;
    @XmlElement(name = "EndDateTrainingPeriode")
    protected Object endDateTrainingPeriode;
    @XmlElement(name = "SchoolDrink")
    protected Object schoolDrink;
    @XmlElement(name = "ParentStatus")
    protected Object parentStatus;
    @XmlElement(name = "TypeOfStay")
    protected Object typeOfStay;
    @XmlElement(name = "DateTypeOfStay")
    protected Object dateTypeOfStay;
    @XmlElement(name = "PGNStudentNumber")
    protected Object pgnStudentNumber;
    @XmlElement(name = "BRON")
    protected Object bron;
    @XmlElement(name = "StartDateDidacticAge")
    protected Object startDateDidacticAge;
    @XmlElement(name = "SchoolCareers")
    protected Student.SchoolCareers schoolCareers;
    @XmlElement(name = "StudentHandicaps")
    protected Student.StudentHandicaps studentHandicaps;
    @XmlElement(name = "StudentRelations")
    protected Student.StudentRelations studentRelations;
    @XmlElement(name = "Denomination")
    protected Denomination denomination;
    @XmlElement(name = "TransportCompany")
    protected Student.TransportCompany transportCompany;
    @XmlElement(name = "GeneralPractioner")
    protected Student.GeneralPractioner generalPractioner;
    @XmlElement(name = "ExtraMedicalAccount")
    protected Student.ExtraMedicalAccount extraMedicalAccount;
    @XmlElement(name = "TrainingPeriodCompany")
    protected Student.TrainingPeriodCompany trainingPeriodCompany;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "code", required = true)
    protected String code;

    /**
     * Gets the value of the studentState property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStudentState() {
        return studentState;
    }

    /**
     * Sets the value of the studentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStudentState(Object value) {
        this.studentState = value;
    }

    /**
     * Gets the value of the nickName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNickName() {
        return nickName;
    }

    /**
     * Sets the value of the nickName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNickName(Object value) {
        this.nickName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFirstName(Object value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMiddleName(Object value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLastName(Object value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFullName(Object value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the addressStreet property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressStreet() {
        return addressStreet;
    }

    /**
     * Sets the value of the addressStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressStreet(Object value) {
        this.addressStreet = value;
    }

    /**
     * Gets the value of the addressStreetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressStreetNumber() {
        return addressStreetNumber;
    }

    /**
     * Sets the value of the addressStreetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressStreetNumber(Object value) {
        this.addressStreetNumber = value;
    }

    /**
     * Gets the value of the addressStreetNumberSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAddressStreetNumberSuffix() {
        return addressStreetNumberSuffix;
    }

    /**
     * Sets the value of the addressStreetNumberSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAddressStreetNumberSuffix(Object value) {
        this.addressStreetNumberSuffix = value;
    }

    /**
     * Gets the value of the streetNumberLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStreetNumberLocation() {
        return streetNumberLocation;
    }

    /**
     * Sets the value of the streetNumberLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStreetNumberLocation(Object value) {
        this.streetNumberLocation = value;
    }

    /**
     * Gets the value of the streetNumberIndication property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStreetNumberIndication() {
        return streetNumberIndication;
    }

    /**
     * Sets the value of the streetNumberIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStreetNumberIndication(Object value) {
        this.streetNumberIndication = value;
    }

    /**
     * Gets the value of the postcode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPostcode() {
        return postcode;
    }

    /**
     * Sets the value of the postcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPostcode(Object value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCity(Object value) {
        this.city = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPhone(Object value) {
        this.phone = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBirthDate(Object value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGender(Object value) {
        this.gender = value;
    }

    /**
     * Gets the value of the countryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCountryOfBirth(Object value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNationality(Object value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the socialSecurityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    /**
     * Sets the value of the socialSecurityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSocialSecurityNumber(Object value) {
        this.socialSecurityNumber = value;
    }

    /**
     * Gets the value of the educationalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEducationalNumber() {
        return educationalNumber;
    }

    /**
     * Sets the value of the educationalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEducationalNumber(Object value) {
        this.educationalNumber = value;
    }

    /**
     * Gets the value of the firstDayAtSchool property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFirstDayAtSchool() {
        return firstDayAtSchool;
    }

    /**
     * Sets the value of the firstDayAtSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFirstDayAtSchool(Object value) {
        this.firstDayAtSchool = value;
    }

    /**
     * Gets the value of the firstLessonDate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFirstLessonDate() {
        return firstLessonDate;
    }

    /**
     * Sets the value of the firstLessonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFirstLessonDate(Object value) {
        this.firstLessonDate = value;
    }

    /**
     * Gets the value of the dateOfDeregistration property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDateOfDeregistration() {
        return dateOfDeregistration;
    }

    /**
     * Sets the value of the dateOfDeregistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDateOfDeregistration(Object value) {
        this.dateOfDeregistration = value;
    }

    /**
     * Gets the value of the transportType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTransportType() {
        return transportType;
    }

    /**
     * Sets the value of the transportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransportType(Object value) {
        this.transportType = value;
    }

    /**
     * Gets the value of the healthInsuranceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getHealthInsuranceNumber() {
        return healthInsuranceNumber;
    }

    /**
     * Sets the value of the healthInsuranceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setHealthInsuranceNumber(Object value) {
        this.healthInsuranceNumber = value;
    }

    /**
     * Gets the value of the secondNationality property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSecondNationality() {
        return secondNationality;
    }

    /**
     * Sets the value of the secondNationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSecondNationality(Object value) {
        this.secondNationality = value;
    }

    /**
     * Gets the value of the voAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVOAdvice() {
        return voAdvice;
    }

    /**
     * Sets the value of the voAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVOAdvice(Object value) {
        this.voAdvice = value;
    }

    /**
     * Gets the value of the preSchoolProgram property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreSchoolProgram() {
        return preSchoolProgram;
    }

    /**
     * Sets the value of the preSchoolProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreSchoolProgram(Object value) {
        this.preSchoolProgram = value;
    }

    /**
     * Gets the value of the schoolType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSchoolType() {
        return schoolType;
    }

    /**
     * Sets the value of the schoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSchoolType(Object value) {
        this.schoolType = value;
    }

    /**
     * Gets the value of the startDateSchoolType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartDateSchoolType() {
        return startDateSchoolType;
    }

    /**
     * Sets the value of the startDateSchoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartDateSchoolType(Object value) {
        this.startDateSchoolType = value;
    }

    /**
     * Gets the value of the educationalType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEducationalType() {
        return educationalType;
    }

    /**
     * Sets the value of the educationalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEducationalType(Object value) {
        this.educationalType = value;
    }

    /**
     * Gets the value of the startDateEducationalType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartDateEducationalType() {
        return startDateEducationalType;
    }

    /**
     * Sets the value of the startDateEducationalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartDateEducationalType(Object value) {
        this.startDateEducationalType = value;
    }

    /**
     * Gets the value of the residential property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getResidential() {
        return residential;
    }

    /**
     * Sets the value of the residential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setResidential(Object value) {
        this.residential = value;
    }

    /**
     * Gets the value of the accompaniment property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAccompaniment() {
        return accompaniment;
    }

    /**
     * Sets the value of the accompaniment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAccompaniment(Object value) {
        this.accompaniment = value;
    }

    /**
     * Gets the value of the startDateTrainingPeriode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartDateTrainingPeriode() {
        return startDateTrainingPeriode;
    }

    /**
     * Sets the value of the startDateTrainingPeriode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartDateTrainingPeriode(Object value) {
        this.startDateTrainingPeriode = value;
    }

    /**
     * Gets the value of the endDateTrainingPeriode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEndDateTrainingPeriode() {
        return endDateTrainingPeriode;
    }

    /**
     * Sets the value of the endDateTrainingPeriode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEndDateTrainingPeriode(Object value) {
        this.endDateTrainingPeriode = value;
    }

    /**
     * Gets the value of the schoolDrink property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSchoolDrink() {
        return schoolDrink;
    }

    /**
     * Sets the value of the schoolDrink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSchoolDrink(Object value) {
        this.schoolDrink = value;
    }

    /**
     * Gets the value of the parentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getParentStatus() {
        return parentStatus;
    }

    /**
     * Sets the value of the parentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setParentStatus(Object value) {
        this.parentStatus = value;
    }

    /**
     * Gets the value of the typeOfStay property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTypeOfStay() {
        return typeOfStay;
    }

    /**
     * Sets the value of the typeOfStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTypeOfStay(Object value) {
        this.typeOfStay = value;
    }

    /**
     * Gets the value of the dateTypeOfStay property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDateTypeOfStay() {
        return dateTypeOfStay;
    }

    /**
     * Sets the value of the dateTypeOfStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDateTypeOfStay(Object value) {
        this.dateTypeOfStay = value;
    }

    /**
     * Gets the value of the pgnStudentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPGNStudentNumber() {
        return pgnStudentNumber;
    }

    /**
     * Sets the value of the pgnStudentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPGNStudentNumber(Object value) {
        this.pgnStudentNumber = value;
    }

    /**
     * Gets the value of the bron property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBRON() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBRON(Object value) {
        this.bron = value;
    }

    /**
     * Gets the value of the startDateDidacticAge property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartDateDidacticAge() {
        return startDateDidacticAge;
    }

    /**
     * Sets the value of the startDateDidacticAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartDateDidacticAge(Object value) {
        this.startDateDidacticAge = value;
    }

    /**
     * Gets the value of the schoolCareers property.
     * 
     * @return
     *     possible object is
     *     {@link Student.SchoolCareers }
     *     
     */
    public Student.SchoolCareers getSchoolCareers() {
        return schoolCareers;
    }

    /**
     * Sets the value of the schoolCareers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.SchoolCareers }
     *     
     */
    public void setSchoolCareers(Student.SchoolCareers value) {
        this.schoolCareers = value;
    }

    /**
     * Gets the value of the studentHandicaps property.
     * 
     * @return
     *     possible object is
     *     {@link Student.StudentHandicaps }
     *     
     */
    public Student.StudentHandicaps getStudentHandicaps() {
        return studentHandicaps;
    }

    /**
     * Sets the value of the studentHandicaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.StudentHandicaps }
     *     
     */
    public void setStudentHandicaps(Student.StudentHandicaps value) {
        this.studentHandicaps = value;
    }

    /**
     * Gets the value of the studentRelations property.
     * 
     * @return
     *     possible object is
     *     {@link Student.StudentRelations }
     *     
     */
    public Student.StudentRelations getStudentRelations() {
        return studentRelations;
    }

    /**
     * Sets the value of the studentRelations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.StudentRelations }
     *     
     */
    public void setStudentRelations(Student.StudentRelations value) {
        this.studentRelations = value;
    }

    /**
     * Gets the value of the denomination property.
     * 
     * @return
     *     possible object is
     *     {@link Denomination }
     *     
     */
    public Denomination getDenomination() {
        return denomination;
    }

    /**
     * Sets the value of the denomination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Denomination }
     *     
     */
    public void setDenomination(Denomination value) {
        this.denomination = value;
    }

    /**
     * Gets the value of the transportCompany property.
     * 
     * @return
     *     possible object is
     *     {@link Student.TransportCompany }
     *     
     */
    public Student.TransportCompany getTransportCompany() {
        return transportCompany;
    }

    /**
     * Sets the value of the transportCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.TransportCompany }
     *     
     */
    public void setTransportCompany(Student.TransportCompany value) {
        this.transportCompany = value;
    }

    /**
     * Gets the value of the generalPractioner property.
     * 
     * @return
     *     possible object is
     *     {@link Student.GeneralPractioner }
     *     
     */
    public Student.GeneralPractioner getGeneralPractioner() {
        return generalPractioner;
    }

    /**
     * Sets the value of the generalPractioner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.GeneralPractioner }
     *     
     */
    public void setGeneralPractioner(Student.GeneralPractioner value) {
        this.generalPractioner = value;
    }

    /**
     * Gets the value of the extraMedicalAccount property.
     * 
     * @return
     *     possible object is
     *     {@link Student.ExtraMedicalAccount }
     *     
     */
    public Student.ExtraMedicalAccount getExtraMedicalAccount() {
        return extraMedicalAccount;
    }

    /**
     * Sets the value of the extraMedicalAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.ExtraMedicalAccount }
     *     
     */
    public void setExtraMedicalAccount(Student.ExtraMedicalAccount value) {
        this.extraMedicalAccount = value;
    }

    /**
     * Gets the value of the trainingPeriodCompany property.
     * 
     * @return
     *     possible object is
     *     {@link Student.TrainingPeriodCompany }
     *     
     */
    public Student.TrainingPeriodCompany getTrainingPeriodCompany() {
        return trainingPeriodCompany;
    }

    /**
     * Sets the value of the trainingPeriodCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link Student.TrainingPeriodCompany }
     *     
     */
    public void setTrainingPeriodCompany(Student.TrainingPeriodCompany value) {
        this.trainingPeriodCompany = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Account"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class ExtraMedicalAccount {

        @XmlElement(name = "Account", required = true)
        protected TypeAccount account;

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAccount }
         *     
         */
        public TypeAccount getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAccount }
         *     
         */
        public void setAccount(TypeAccount value) {
            this.account = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Account"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class GeneralPractioner {

        @XmlElement(name = "Account", required = true)
        protected TypeAccount account;

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAccount }
         *     
         */
        public TypeAccount getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAccount }
         *     
         */
        public void setAccount(TypeAccount value) {
            this.account = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}SchoolCareer" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schoolCareer"
    })
    public static class SchoolCareers {

        @XmlElement(name = "SchoolCareer", required = true)
        protected List<SchoolCareer> schoolCareer;

        /**
         * Gets the value of the schoolCareer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the schoolCareer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSchoolCareer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SchoolCareer }
         * 
         * 
         */
        public List<SchoolCareer> getSchoolCareer() {
            if (schoolCareer == null) {
                schoolCareer = new ArrayList<SchoolCareer>();
            }
            return this.schoolCareer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}StudentHandicap" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "studentHandicap"
    })
    public static class StudentHandicaps {

        @XmlElement(name = "StudentHandicap", required = true)
        protected List<StudentHandicap> studentHandicap;

        /**
         * Gets the value of the studentHandicap property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the studentHandicap property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStudentHandicap().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StudentHandicap }
         * 
         * 
         */
        public List<StudentHandicap> getStudentHandicap() {
            if (studentHandicap == null) {
                studentHandicap = new ArrayList<StudentHandicap>();
            }
            return this.studentHandicap;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}StudentRelation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "studentRelation"
    })
    public static class StudentRelations {

        @XmlElement(name = "StudentRelation", required = true)
        protected List<StudentRelation> studentRelation;

        /**
         * Gets the value of the studentRelation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the studentRelation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStudentRelation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StudentRelation }
         * 
         * 
         */
        public List<StudentRelation> getStudentRelation() {
            if (studentRelation == null) {
                studentRelation = new ArrayList<StudentRelation>();
            }
            return this.studentRelation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Account"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class TrainingPeriodCompany {

        @XmlElement(name = "Account", required = true)
        protected TypeAccount account;

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAccount }
         *     
         */
        public TypeAccount getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAccount }
         *     
         */
        public void setAccount(TypeAccount value) {
            this.account = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Account"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class TransportCompany {

        @XmlElement(name = "Account", required = true)
        protected TypeAccount account;

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link TypeAccount }
         *     
         */
        public TypeAccount getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeAccount }
         *     
         */
        public void setAccount(TypeAccount value) {
            this.account = value;
        }

    }

}
