//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for typeAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeAccount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Phone" minOccurs="0"/>
 *         &lt;element ref="{}PhoneExt" minOccurs="0"/>
 *         &lt;element ref="{}Fax" minOccurs="0"/>
 *         &lt;element ref="{}Email" minOccurs="0"/>
 *         &lt;element ref="{}HomePage" minOccurs="0"/>
 *         &lt;element ref="{}Language" minOccurs="0"/>
 *         &lt;element name="IsSupplier" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CanDropShip" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsBlocked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsReseller" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsPilot" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsSales" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsPurchase" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsMember" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsAccountant" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="CodeAtSupplier" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Reseller" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute ref="{}code"/>
 *                 &lt;attribute ref="{}ID"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Contact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}BankAccount" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccountManager" type="{}typeUser" minOccurs="0"/>
 *         &lt;element ref="{}Image" minOccurs="0"/>
 *         &lt;element ref="{}Note" minOccurs="0"/>
 *         &lt;element name="VATSales" type="{}VAT" minOccurs="0"/>
 *         &lt;element name="VATPurchase" type="{}VAT" minOccurs="0"/>
 *         &lt;element name="VATNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VATLiability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChamberOfCommerce" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DunsNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}Currency" minOccurs="0"/>
 *         &lt;element name="SecurityLevel" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{}CreditLine" minOccurs="0"/>
 *         &lt;element name="PriceList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute ref="{}code"/>
 *                 &lt;attribute ref="{}ID"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceAccount" type="{}typeAccount" minOccurs="0"/>
 *         &lt;element name="Discount" type="{}AccountDiscount" minOccurs="0"/>
 *         &lt;element name="CostRevenueDirectAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="GLPurchase" type="{}typeGLAccount" minOccurs="0"/>
 *         &lt;element name="GLSales" type="{}typeGLAccount" minOccurs="0"/>
 *         &lt;element name="GLAP" type="{}typeGLAccount" minOccurs="0"/>
 *         &lt;element name="GLAR" type="{}typeGLAccount" minOccurs="0"/>
 *         &lt;element name="SalesPaymentCondition" type="{}PaymentCondition" minOccurs="0"/>
 *         &lt;element name="PurchasePaymentCondition" type="{}PaymentCondition" minOccurs="0"/>
 *         &lt;element name="CreditManagementScenario" type="{}typeCreditManagementScenario" minOccurs="0"/>
 *         &lt;element name="CreditManagementStatus" type="{}typeCreditManagementStatus" minOccurs="0"/>
 *         &lt;element ref="{}Classification" minOccurs="0"/>
 *         &lt;element name="Sector" type="{}ActivitySectorType" minOccurs="0"/>
 *         &lt;element name="SubSector" type="{}ActivitySectorType" minOccurs="0"/>
 *         &lt;element ref="{}CompanySize" minOccurs="0"/>
 *         &lt;element ref="{}BusinessType" minOccurs="0"/>
 *         &lt;element ref="{}LeadSource" minOccurs="0"/>
 *         &lt;element name="IsMailing" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsCompetitor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{}StartDate" minOccurs="0"/>
 *         &lt;element ref="{}EndDate" minOccurs="0"/>
 *         &lt;element name="IsInactive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CustomerSince" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatusSince" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntraStat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="TransactionA" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="TransactionB" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="TransportMethod" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="DeliveryTerm" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="Area" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoicingMethod" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}code"/>
 *       &lt;attribute name="searchcode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value=""/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="A"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute ref="{}ID"/>
 *       &lt;attribute name="Accountant" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeAccount", propOrder = {
    "name",
    "phone",
    "phoneExt",
    "fax",
    "email",
    "homePage",
    "language",
    "isSupplier",
    "canDropShip",
    "isBlocked",
    "isReseller",
    "isPilot",
    "isSales",
    "isPurchase",
    "isMember",
    "isAccountant",
    "codeAtSupplier",
    "reseller",
    "contact",
    "address",
    "bankAccount",
    "accountManager",
    "image",
    "note",
    "vatSales",
    "vatPurchase",
    "vatNumber",
    "vatLiability",
    "chamberOfCommerce",
    "dunsNumber",
    "currency",
    "securityLevel",
    "creditLine",
    "priceList",
    "invoiceAccount",
    "discount",
    "costRevenueDirectAllowed",
    "glPurchase",
    "glSales",
    "glap",
    "glar",
    "salesPaymentCondition",
    "purchasePaymentCondition",
    "creditManagementScenario",
    "creditManagementStatus",
    "classification",
    "sector",
    "subSector",
    "companySize",
    "businessType",
    "leadSource",
    "isMailing",
    "isCompetitor",
    "startDate",
    "endDate",
    "isInactive",
    "customerSince",
    "statusSince",
    "intraStat",
    "invoicingMethod"
})
public class TypeAccount {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Phone")
    protected String phone;
    @XmlElement(name = "PhoneExt")
    protected String phoneExt;
    @XmlElement(name = "Fax")
    protected String fax;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "HomePage")
    protected String homePage;
    @XmlElement(name = "Language")
    protected Language language;
    @XmlElement(name = "IsSupplier")
    protected Boolean isSupplier;
    @XmlElement(name = "CanDropShip")
    protected Boolean canDropShip;
    @XmlElement(name = "IsBlocked")
    protected Boolean isBlocked;
    @XmlElement(name = "IsReseller")
    protected Boolean isReseller;
    @XmlElement(name = "IsPilot")
    protected Boolean isPilot;
    @XmlElement(name = "IsSales")
    protected Boolean isSales;
    @XmlElement(name = "IsPurchase")
    protected Boolean isPurchase;
    @XmlElement(name = "IsMember")
    protected Boolean isMember;
    @XmlElement(name = "IsAccountant")
    protected BigInteger isAccountant;
    @XmlElement(name = "CodeAtSupplier")
    protected Object codeAtSupplier;
    @XmlElement(name = "Reseller")
    protected TypeAccount.Reseller reseller;
    @XmlElement(name = "Contact")
    protected List<Contact> contact;
    @XmlElement(name = "Address")
    protected List<Address> address;
    @XmlElement(name = "BankAccount")
    protected List<BankAccount> bankAccount;
    @XmlElement(name = "AccountManager")
    protected TypeUser accountManager;
    @XmlElement(name = "Image")
    protected Image image;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "VATSales")
    protected VAT vatSales;
    @XmlElement(name = "VATPurchase")
    protected VAT vatPurchase;
    @XmlElement(name = "VATNumber")
    protected String vatNumber;
    @XmlElement(name = "VATLiability")
    protected String vatLiability;
    @XmlElement(name = "ChamberOfCommerce")
    protected String chamberOfCommerce;
    @XmlElement(name = "DunsNumber")
    protected String dunsNumber;
    @XmlElement(name = "Currency")
    protected Currency currency;
    @XmlElement(name = "SecurityLevel")
    protected BigInteger securityLevel;
    @XmlElement(name = "CreditLine")
    protected CreditLine creditLine;
    @XmlElement(name = "PriceList")
    protected TypeAccount.PriceList priceList;
    @XmlElement(name = "InvoiceAccount")
    protected TypeAccount invoiceAccount;
    @XmlElement(name = "Discount")
    protected AccountDiscount discount;
    @XmlElement(name = "CostRevenueDirectAllowed")
    protected Boolean costRevenueDirectAllowed;
    @XmlElement(name = "GLPurchase")
    protected TypeGLAccount glPurchase;
    @XmlElement(name = "GLSales")
    protected TypeGLAccount glSales;
    @XmlElement(name = "GLAP")
    protected TypeGLAccount glap;
    @XmlElement(name = "GLAR")
    protected TypeGLAccount glar;
    @XmlElement(name = "SalesPaymentCondition")
    protected PaymentCondition salesPaymentCondition;
    @XmlElement(name = "PurchasePaymentCondition")
    protected PaymentCondition purchasePaymentCondition;
    @XmlElement(name = "CreditManagementScenario")
    protected TypeCreditManagementScenario creditManagementScenario;
    @XmlElement(name = "CreditManagementStatus")
    protected TypeCreditManagementStatus creditManagementStatus;
    @XmlElement(name = "Classification")
    protected Classification classification;
    @XmlElement(name = "Sector")
    protected ActivitySectorType sector;
    @XmlElement(name = "SubSector")
    protected ActivitySectorType subSector;
    @XmlElement(name = "CompanySize")
    protected CompanySize companySize;
    @XmlElement(name = "BusinessType")
    protected BusinessType businessType;
    @XmlElement(name = "LeadSource")
    protected LeadSource leadSource;
    @XmlElement(name = "IsMailing")
    protected Boolean isMailing;
    @XmlElement(name = "IsCompetitor")
    protected Boolean isCompetitor;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "IsInactive")
    protected Boolean isInactive;
    @XmlElement(name = "CustomerSince")
    protected String customerSince;
    @XmlElement(name = "StatusSince")
    protected String statusSince;
    @XmlElement(name = "IntraStat")
    protected TypeAccount.IntraStat intraStat;
    @XmlElement(name = "InvoicingMethod")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String invoicingMethod;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "searchcode")
    @XmlSchemaType(name = "anySimpleType")
    protected String searchcode;
    @XmlAttribute(name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Accountant")
    @XmlSchemaType(name = "anySimpleType")
    protected String accountant;

    public TypeAccount() {
    }

    public TypeAccount(String code) {
        this.code = code;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the phoneExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneExt() {
        return phoneExt;
    }

    /**
     * Sets the value of the phoneExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneExt(String value) {
        this.phoneExt = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the homePage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePage() {
        return homePage;
    }

    /**
     * Sets the value of the homePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePage(String value) {
        this.homePage = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(Language value) {
        this.language = value;
    }

    /**
     * Gets the value of the isSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSupplier() {
        return isSupplier;
    }

    /**
     * Sets the value of the isSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSupplier(Boolean value) {
        this.isSupplier = value;
    }

    /**
     * Gets the value of the canDropShip property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanDropShip() {
        return canDropShip;
    }

    /**
     * Sets the value of the canDropShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanDropShip(Boolean value) {
        this.canDropShip = value;
    }

    /**
     * Gets the value of the isBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBlocked() {
        return isBlocked;
    }

    /**
     * Sets the value of the isBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBlocked(Boolean value) {
        this.isBlocked = value;
    }

    /**
     * Gets the value of the isReseller property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsReseller() {
        return isReseller;
    }

    /**
     * Sets the value of the isReseller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReseller(Boolean value) {
        this.isReseller = value;
    }

    /**
     * Gets the value of the isPilot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPilot() {
        return isPilot;
    }

    /**
     * Sets the value of the isPilot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPilot(Boolean value) {
        this.isPilot = value;
    }

    /**
     * Gets the value of the isSales property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSales() {
        return isSales;
    }

    /**
     * Sets the value of the isSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSales(Boolean value) {
        this.isSales = value;
    }

    /**
     * Gets the value of the isPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPurchase() {
        return isPurchase;
    }

    /**
     * Sets the value of the isPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPurchase(Boolean value) {
        this.isPurchase = value;
    }

    /**
     * Gets the value of the isMember property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMember() {
        return isMember;
    }

    /**
     * Sets the value of the isMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMember(Boolean value) {
        this.isMember = value;
    }

    /**
     * Gets the value of the isAccountant property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsAccountant() {
        return isAccountant;
    }

    /**
     * Sets the value of the isAccountant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsAccountant(BigInteger value) {
        this.isAccountant = value;
    }

    /**
     * Gets the value of the codeAtSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCodeAtSupplier() {
        return codeAtSupplier;
    }

    /**
     * Sets the value of the codeAtSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCodeAtSupplier(Object value) {
        this.codeAtSupplier = value;
    }

    /**
     * Gets the value of the reseller property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount.Reseller }
     *     
     */
    public TypeAccount.Reseller getReseller() {
        return reseller;
    }

    /**
     * Sets the value of the reseller property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount.Reseller }
     *     
     */
    public void setReseller(TypeAccount.Reseller value) {
        this.reseller = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contact }
     * 
     * 
     */
    public List<Contact> getContact() {
        if (contact == null) {
            contact = new ArrayList<Contact>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the bankAccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankAccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankAccount }
     * 
     * 
     */
    public List<BankAccount> getBankAccount() {
        if (bankAccount == null) {
            bankAccount = new ArrayList<BankAccount>();
        }
        return this.bankAccount;
    }

    /**
     * Gets the value of the accountManager property.
     * 
     * @return
     *     possible object is
     *     {@link TypeUser }
     *     
     */
    public TypeUser getAccountManager() {
        return accountManager;
    }

    /**
     * Sets the value of the accountManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeUser }
     *     
     */
    public void setAccountManager(TypeUser value) {
        this.accountManager = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Image }
     *     
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image }
     *     
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the vatSales property.
     * 
     * @return
     *     possible object is
     *     {@link VAT }
     *     
     */
    public VAT getVATSales() {
        return vatSales;
    }

    /**
     * Sets the value of the vatSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link VAT }
     *     
     */
    public void setVATSales(VAT value) {
        this.vatSales = value;
    }

    /**
     * Gets the value of the vatPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link VAT }
     *     
     */
    public VAT getVATPurchase() {
        return vatPurchase;
    }

    /**
     * Sets the value of the vatPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link VAT }
     *     
     */
    public void setVATPurchase(VAT value) {
        this.vatPurchase = value;
    }

    /**
     * Gets the value of the vatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATNumber() {
        return vatNumber;
    }

    /**
     * Sets the value of the vatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATNumber(String value) {
        this.vatNumber = value;
    }

    /**
     * Gets the value of the vatLiability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATLiability() {
        return vatLiability;
    }

    /**
     * Sets the value of the vatLiability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATLiability(String value) {
        this.vatLiability = value;
    }

    /**
     * Gets the value of the chamberOfCommerce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChamberOfCommerce() {
        return chamberOfCommerce;
    }

    /**
     * Sets the value of the chamberOfCommerce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChamberOfCommerce(String value) {
        this.chamberOfCommerce = value;
    }

    /**
     * Gets the value of the dunsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDunsNumber() {
        return dunsNumber;
    }

    /**
     * Sets the value of the dunsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDunsNumber(String value) {
        this.dunsNumber = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCurrency(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the securityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecurityLevel() {
        return securityLevel;
    }

    /**
     * Sets the value of the securityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecurityLevel(BigInteger value) {
        this.securityLevel = value;
    }

    /**
     * Gets the value of the creditLine property.
     * 
     * @return
     *     possible object is
     *     {@link CreditLine }
     *     
     */
    public CreditLine getCreditLine() {
        return creditLine;
    }

    /**
     * Sets the value of the creditLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditLine }
     *     
     */
    public void setCreditLine(CreditLine value) {
        this.creditLine = value;
    }

    /**
     * Gets the value of the priceList property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount.PriceList }
     *     
     */
    public TypeAccount.PriceList getPriceList() {
        return priceList;
    }

    /**
     * Sets the value of the priceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount.PriceList }
     *     
     */
    public void setPriceList(TypeAccount.PriceList value) {
        this.priceList = value;
    }

    /**
     * Gets the value of the invoiceAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount }
     *     
     */
    public TypeAccount getInvoiceAccount() {
        return invoiceAccount;
    }

    /**
     * Sets the value of the invoiceAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount }
     *     
     */
    public void setInvoiceAccount(TypeAccount value) {
        this.invoiceAccount = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDiscount }
     *     
     */
    public AccountDiscount getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDiscount }
     *     
     */
    public void setDiscount(AccountDiscount value) {
        this.discount = value;
    }

    /**
     * Gets the value of the costRevenueDirectAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCostRevenueDirectAllowed() {
        return costRevenueDirectAllowed;
    }

    /**
     * Sets the value of the costRevenueDirectAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCostRevenueDirectAllowed(Boolean value) {
        this.costRevenueDirectAllowed = value;
    }

    /**
     * Gets the value of the glPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLPurchase() {
        return glPurchase;
    }

    /**
     * Sets the value of the glPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLPurchase(TypeGLAccount value) {
        this.glPurchase = value;
    }

    /**
     * Gets the value of the glSales property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLSales() {
        return glSales;
    }

    /**
     * Sets the value of the glSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLSales(TypeGLAccount value) {
        this.glSales = value;
    }

    /**
     * Gets the value of the glap property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLAP() {
        return glap;
    }

    /**
     * Sets the value of the glap property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLAP(TypeGLAccount value) {
        this.glap = value;
    }

    /**
     * Gets the value of the glar property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGLAccount }
     *     
     */
    public TypeGLAccount getGLAR() {
        return glar;
    }

    /**
     * Sets the value of the glar property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGLAccount }
     *     
     */
    public void setGLAR(TypeGLAccount value) {
        this.glar = value;
    }

    /**
     * Gets the value of the salesPaymentCondition property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCondition }
     *     
     */
    public PaymentCondition getSalesPaymentCondition() {
        return salesPaymentCondition;
    }

    /**
     * Sets the value of the salesPaymentCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCondition }
     *     
     */
    public void setSalesPaymentCondition(PaymentCondition value) {
        this.salesPaymentCondition = value;
    }

    /**
     * Gets the value of the purchasePaymentCondition property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCondition }
     *     
     */
    public PaymentCondition getPurchasePaymentCondition() {
        return purchasePaymentCondition;
    }

    /**
     * Sets the value of the purchasePaymentCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCondition }
     *     
     */
    public void setPurchasePaymentCondition(PaymentCondition value) {
        this.purchasePaymentCondition = value;
    }

    /**
     * Gets the value of the creditManagementScenario property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCreditManagementScenario }
     *     
     */
    public TypeCreditManagementScenario getCreditManagementScenario() {
        return creditManagementScenario;
    }

    /**
     * Sets the value of the creditManagementScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCreditManagementScenario }
     *     
     */
    public void setCreditManagementScenario(TypeCreditManagementScenario value) {
        this.creditManagementScenario = value;
    }

    /**
     * Gets the value of the creditManagementStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCreditManagementStatus }
     *     
     */
    public TypeCreditManagementStatus getCreditManagementStatus() {
        return creditManagementStatus;
    }

    /**
     * Sets the value of the creditManagementStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCreditManagementStatus }
     *     
     */
    public void setCreditManagementStatus(TypeCreditManagementStatus value) {
        this.creditManagementStatus = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link Classification }
     *     
     */
    public Classification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classification }
     *     
     */
    public void setClassification(Classification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the sector property.
     * 
     * @return
     *     possible object is
     *     {@link ActivitySectorType }
     *     
     */
    public ActivitySectorType getSector() {
        return sector;
    }

    /**
     * Sets the value of the sector property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivitySectorType }
     *     
     */
    public void setSector(ActivitySectorType value) {
        this.sector = value;
    }

    /**
     * Gets the value of the subSector property.
     * 
     * @return
     *     possible object is
     *     {@link ActivitySectorType }
     *     
     */
    public ActivitySectorType getSubSector() {
        return subSector;
    }

    /**
     * Sets the value of the subSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivitySectorType }
     *     
     */
    public void setSubSector(ActivitySectorType value) {
        this.subSector = value;
    }

    /**
     * Gets the value of the companySize property.
     * 
     * @return
     *     possible object is
     *     {@link CompanySize }
     *     
     */
    public CompanySize getCompanySize() {
        return companySize;
    }

    /**
     * Sets the value of the companySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanySize }
     *     
     */
    public void setCompanySize(CompanySize value) {
        this.companySize = value;
    }

    /**
     * Gets the value of the businessType property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessType }
     *     
     */
    public BusinessType getBusinessType() {
        return businessType;
    }

    /**
     * Sets the value of the businessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessType }
     *     
     */
    public void setBusinessType(BusinessType value) {
        this.businessType = value;
    }

    /**
     * Gets the value of the leadSource property.
     * 
     * @return
     *     possible object is
     *     {@link LeadSource }
     *     
     */
    public LeadSource getLeadSource() {
        return leadSource;
    }

    /**
     * Sets the value of the leadSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeadSource }
     *     
     */
    public void setLeadSource(LeadSource value) {
        this.leadSource = value;
    }

    /**
     * Gets the value of the isMailing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMailing() {
        return isMailing;
    }

    /**
     * Sets the value of the isMailing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMailing(Boolean value) {
        this.isMailing = value;
    }

    /**
     * Gets the value of the isCompetitor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCompetitor() {
        return isCompetitor;
    }

    /**
     * Sets the value of the isCompetitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCompetitor(Boolean value) {
        this.isCompetitor = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the isInactive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInactive() {
        return isInactive;
    }

    /**
     * Sets the value of the isInactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInactive(Boolean value) {
        this.isInactive = value;
    }

    /**
     * Gets the value of the customerSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerSince() {
        return customerSince;
    }

    /**
     * Sets the value of the customerSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerSince(String value) {
        this.customerSince = value;
    }

    /**
     * Gets the value of the statusSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusSince() {
        return statusSince;
    }

    /**
     * Sets the value of the statusSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusSince(String value) {
        this.statusSince = value;
    }

    /**
     * Gets the value of the intraStat property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount.IntraStat }
     *     
     */
    public TypeAccount.IntraStat getIntraStat() {
        return intraStat;
    }

    /**
     * Sets the value of the intraStat property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount.IntraStat }
     *     
     */
    public void setIntraStat(TypeAccount.IntraStat value) {
        this.intraStat = value;
    }

    /**
     * Gets the value of the invoicingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoicingMethod() {
        return invoicingMethod;
    }

    /**
     * Sets the value of the invoicingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoicingMethod(String value) {
        this.invoicingMethod = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the searchcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchcode() {
        return searchcode;
    }

    /**
     * Sets the value of the searchcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchcode(String value) {
        this.searchcode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the accountant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountant() {
        return accountant;
    }

    /**
     * Sets the value of the accountant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountant(String value) {
        this.accountant = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="TransactionA" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="TransactionB" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="TransportMethod" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="DeliveryTerm" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="Area" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "system",
        "transactionA",
        "transactionB",
        "transportMethod",
        "deliveryTerm",
        "area"
    })
    public static class IntraStat {

        @XmlElement(name = "System")
        protected Object system;
        @XmlElement(name = "TransactionA")
        protected Object transactionA;
        @XmlElement(name = "TransactionB")
        protected Object transactionB;
        @XmlElement(name = "TransportMethod")
        protected Object transportMethod;
        @XmlElement(name = "DeliveryTerm")
        protected Object deliveryTerm;
        @XmlElement(name = "Area")
        protected Object area;

        /**
         * Gets the value of the system property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSystem(Object value) {
            this.system = value;
        }

        /**
         * Gets the value of the transactionA property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTransactionA() {
            return transactionA;
        }

        /**
         * Sets the value of the transactionA property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTransactionA(Object value) {
            this.transactionA = value;
        }

        /**
         * Gets the value of the transactionB property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTransactionB() {
            return transactionB;
        }

        /**
         * Sets the value of the transactionB property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTransactionB(Object value) {
            this.transactionB = value;
        }

        /**
         * Gets the value of the transportMethod property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTransportMethod() {
            return transportMethod;
        }

        /**
         * Sets the value of the transportMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTransportMethod(Object value) {
            this.transportMethod = value;
        }

        /**
         * Gets the value of the deliveryTerm property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeliveryTerm() {
            return deliveryTerm;
        }

        /**
         * Sets the value of the deliveryTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeliveryTerm(Object value) {
            this.deliveryTerm = value;
        }

        /**
         * Gets the value of the area property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getArea() {
            return area;
        }

        /**
         * Sets the value of the area property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setArea(Object value) {
            this.area = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute ref="{}code"/>
     *       &lt;attribute ref="{}ID"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PriceList {

        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "ID")
        protected String id;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute ref="{}code"/>
     *       &lt;attribute ref="{}ID"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Reseller {

        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "ID")
        protected String id;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }

}
