//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for typeCreditManagementScenarioRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeCreditManagementScenarioRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Description"/>
 *         &lt;element name="Action">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ActionStart">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="numberofdays" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NewStatusPaymentTerm" type="{}typeCreditManagementStatus" minOccurs="0"/>
 *         &lt;element name="NewStatusAccount" type="{}typeCreditManagementStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}ID"/>
 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isactive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeCreditManagementScenarioRule", propOrder = {
    "description",
    "action",
    "actionStart",
    "newStatusPaymentTerm",
    "newStatusAccount"
})
public class TypeCreditManagementScenarioRule {

    @XmlElement(name = "Description", required = true)
    protected TypeDescription description;
    @XmlElement(name = "Action", required = true)
    protected TypeCreditManagementScenarioRule.Action action;
    @XmlElement(name = "ActionStart", required = true)
    protected TypeCreditManagementScenarioRule.ActionStart actionStart;
    @XmlElement(name = "NewStatusPaymentTerm")
    protected TypeCreditManagementStatus newStatusPaymentTerm;
    @XmlElement(name = "NewStatusAccount")
    protected TypeCreditManagementStatus newStatusAccount;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "number", required = true)
    protected BigInteger number;
    @XmlAttribute(name = "isactive")
    protected Boolean isactive;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setDescription(TypeDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCreditManagementScenarioRule.Action }
     *     
     */
    public TypeCreditManagementScenarioRule.Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCreditManagementScenarioRule.Action }
     *     
     */
    public void setAction(TypeCreditManagementScenarioRule.Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the actionStart property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCreditManagementScenarioRule.ActionStart }
     *     
     */
    public TypeCreditManagementScenarioRule.ActionStart getActionStart() {
        return actionStart;
    }

    /**
     * Sets the value of the actionStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCreditManagementScenarioRule.ActionStart }
     *     
     */
    public void setActionStart(TypeCreditManagementScenarioRule.ActionStart value) {
        this.actionStart = value;
    }

    /**
     * Gets the value of the newStatusPaymentTerm property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCreditManagementStatus }
     *     
     */
    public TypeCreditManagementStatus getNewStatusPaymentTerm() {
        return newStatusPaymentTerm;
    }

    /**
     * Sets the value of the newStatusPaymentTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCreditManagementStatus }
     *     
     */
    public void setNewStatusPaymentTerm(TypeCreditManagementStatus value) {
        this.newStatusPaymentTerm = value;
    }

    /**
     * Gets the value of the newStatusAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCreditManagementStatus }
     *     
     */
    public TypeCreditManagementStatus getNewStatusAccount() {
        return newStatusAccount;
    }

    /**
     * Sets the value of the newStatusAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCreditManagementStatus }
     *     
     */
    public void setNewStatusAccount(TypeCreditManagementStatus value) {
        this.newStatusAccount = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the isactive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsactive() {
        return isactive;
    }

    /**
     * Sets the value of the isactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsactive(Boolean value) {
        this.isactive = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Action {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "id", required = true)
        protected BigInteger id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="numberofdays" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ActionStart {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "id", required = true)
        protected BigInteger id;
        @XmlAttribute(name = "numberofdays")
        protected BigInteger numberofdays;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the numberofdays property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberofdays() {
            return numberofdays;
        }

        /**
         * Sets the value of the numberofdays property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberofdays(BigInteger value) {
            this.numberofdays = value;
        }

    }

}
