//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeLegislationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeLegislationEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Belgium"/>
 *     &lt;enumeration value="Germany"/>
 *     &lt;enumeration value="Luxembourg"/>
 *     &lt;enumeration value="Netherlands"/>
 *     &lt;enumeration value="NetherlandsAntilles"/>
 *     &lt;enumeration value="Turkey"/>
 *     &lt;enumeration value="UnitedKingdom"/>
 *     &lt;enumeration value="France"/>
 *     &lt;enumeration value="UnitedStates"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeLegislationEnum")
@XmlEnum
public enum TypeLegislationEnum {

    @XmlEnumValue("Belgium")
    BELGIUM("Belgium"),
    @XmlEnumValue("Germany")
    GERMANY("Germany"),
    @XmlEnumValue("Luxembourg")
    LUXEMBOURG("Luxembourg"),
    @XmlEnumValue("Netherlands")
    NETHERLANDS("Netherlands"),
    @XmlEnumValue("NetherlandsAntilles")
    NETHERLANDS_ANTILLES("NetherlandsAntilles"),
    @XmlEnumValue("Turkey")
    TURKEY("Turkey"),
    @XmlEnumValue("UnitedKingdom")
    UNITED_KINGDOM("UnitedKingdom"),
    @XmlEnumValue("France")
    FRANCE("France"),
    @XmlEnumValue("UnitedStates")
    UNITED_STATES("UnitedStates");
    private final String value;

    TypeLegislationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeLegislationEnum fromValue(String v) {
        for (TypeLegislationEnum c: TypeLegislationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
