//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:28:10 PM CEST 
//


package com.mipagar.exact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}VATBox"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sign">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="I"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="O"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="Q"/>
 *             &lt;enumeration value="R"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="V"/>
 *             &lt;enumeration value="W"/>
 *             &lt;enumeration value="X"/>
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="Z"/>
 *             &lt;enumeration value="J"/>
 *             &lt;enumeration value="K"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VATGLAccountType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="D"/>
 *             &lt;enumeration value="G"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vatBox"
})
@XmlRootElement(name = "VATBoxLink")
public class VATBoxLink {

    @XmlElement(name = "VATBox")
    protected VATBox vatBox;
    @XmlAttribute(name = "sign")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sign;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "VATGLAccountType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String vatglAccountType;

    /**
     * Gets the value of the vatBox property.
     * 
     * @return
     *     possible object is
     *     {@link VATBox }
     *     
     */
    public VATBox getVATBox() {
        return vatBox;
    }

    /**
     * Sets the value of the vatBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link VATBox }
     *     
     */
    public void setVATBox(VATBox value) {
        this.vatBox = value;
    }

    /**
     * Gets the value of the sign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSign() {
        return sign;
    }

    /**
     * Sets the value of the sign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSign(String value) {
        this.sign = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the vatglAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATGLAccountType() {
        return vatglAccountType;
    }

    /**
     * Sets the value of the vatglAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATGLAccountType(String value) {
        this.vatglAccountType = value;
    }

}
